---
title: "Exercise"
author: "Jiaxin Shen"
format: html
execute: 
  keep-md: true
---

```{r}
#| message: false
here::i_am("r-101-grade-analysis.Rproj")
library(here)
library(vroom)
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
```

## Exercise 1

```{r}
#| message: false
grades <- vroom(here("grades.csv"))
```

## Exercise2

```{r}
T1 <- grades |>
  summarise(min_Grade=min(Exam,na.rm=TRUE),
            max_Grade=max(Exam,na.rm=TRUE),
            mean_Grade=mean(Exam,na.rm=TRUE),
            median_Grade=median(Exam,na.rm=TRUE))
knitr::kable(T1)
```

## Exercise 3

```{r}
N <- sum(is.na(grades$Exam))
```
The number of students who did not take the final exam is  `r N`.

## Exercise 4
```{r message=FALSE,warning=FALSE}
ggplot(grades, aes(x = Exam)) +
  geom_bar()+
  xlab("Grade") +
  ylab("Number of the students")
```

## Exercise 5
```{r}
T2 <- grades |>
  group_by(Group) |>
  summarise(number=n())
knitr::kable(T2)
```

## Exercise 6
```{r message=FALSE,warning=FALSE}
ggplot(grades, aes(x = Group)) +
  geom_bar()+
  xlab("Group") +
  ylab("Number of the students")
```

## Exercise 7
```{r message=FALSE,warning=FALSE}
ggplot(grades, aes(x = Exam)) +
  geom_bar()+
  facet_wrap(vars(Group),scales = "free_x")+
  scale_x_continuous(breaks = c(0,5,10,15,20))+
  xlab("Grade")+
  ylab("Number of students")
```

```{r message=FALSE,warning=FALSE}
ggplot(grades, aes(x = Exam, color=Group)) +
  geom_bar()+
  scale_x_continuous(breaks = c(0,5,10,15,20))+
  xlab("Grade")+
  ylab("Number of students")
```

## Exercise 8
```{r}
T3 <- grades |> 
    group_by(`Group`) |>
    summarize(number = sum(is.na(Exam)))
```

## Exercise 9
```{r message=FALSE,warning=FALSE}
ggplot(T3, aes(x = Group, y = number)) +
  geom_col()+
  xlab("Group")+
  ylab("Missed Exam")
```

## Exercise 10
```{r}
options(digits=3)
T4 <- grades |>
  pivot_longer(!Id & !Group,names_to = "name", values_to = "Value")
```

## Exercise 11
```{r}
T5 <- T4 |> 
    group_by(`Id`) |>
    summarize(missing_grades = sum(is.na(Value)))
```

## Exercise 12
```{r}
ggplot(T5, aes(x = Id, y = missing_grades)) +
  geom_col()+
  xlab("Id")+
  ylab("Missing grades")
```

## Exercise 13
```{r}
T6 <- T4 |> 
    filter(str_starts(name,"Exam")) |>
    group_by(Group) |>  
    summarise(n = sum(is.na(Value)))
knitr::kable(T6)
```

## Exercise 14
```{r}
T7 <- T4 |> 
    filter(str_starts(name,"Online_MCQ_")) |>
    group_by(`Id`) |>
    summarize(missing_online_grades = sum(is.na(Value)))
```

## Exercise 15
```{r message=FALSE,warning=FALSE}
T8 <- inner_join(T7,grades,by="Id")
ggplot(T8, aes(x = Exam)) +
  geom_bar()+
  facet_wrap(vars(missing_online_grades), scales = "free_y")+
  xlab("Exam Grade")+
  ylab("Number")
```

## Exercise 16
```{r}
T9 <- T4 |>
  filter(str_starts(name,"MCQ_")) |>
  group_by(`Id`) |>
  summarize(Missed = isTRUE(sum(is.na(Value))>=1))
```

## Exercise 17
```{r}
T10 <- inner_join(T9,grades,by="Id") |>
  count(Group, Missed) |>
  group_by(Group) |>
  mutate(P_misssed=n/sum(n)) |>
  ungroup() |>
  filter(Missed=="TRUE") |>
  select(Group,P_misssed)
```

## Exercise 18
```{r}
T11 <- grades |>
  group_by(Group) |>
  summarise(Average_Grade=mean(Exam,na.rm=TRUE)) |>
  inner_join(T10,by="Group")
```

```{r}
ggplot(T11, aes(x=P_misssed,y=Average_Grade)) +
geom_hex()
```
